---
- hosts: all
  sudo: yes
  tasks:
      - name: link /mos -> /vagrant
        file: src=/vagrant
              dest=/mos
              state=link

# check the existence of the secret_key.py file and create one if it does not exist
      - stat: path=/mos/mos/settings/secret_key.py
        register: st
      - shell: echo "SECRET_KEY='start123'" > /mos/mos/settings/secret_key.py
        when: st.stat.exists == False

# update / install packages
      - apt: update_cache=yes

#      - apt: pkg=python-dev
      - apt: pkg=build-essential
#      - apt: pkg=python-pip

# install required python modules
      - pip: requirements=/vagrant/requirements.txt
      - pip: requirements=/vagrant/requirements-dev.txt

#      - name: add locale de_DE
#        lineinfile: dest=/etc/locale.gen
#                    regexp='^#\s*(de_DE.UTF-8\s*UTF-8)'
#                    line='\1'
#                    backrefs=yes

#      - name: reconfigure locales
#        command: free_form='DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales'

#      sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales


# prepare MOS itself
      - name: django syncdb
        django_manage: app_path=/mos
                       command=syncdb

      - name: django migrate
        django_manage: app_path=/mos
                       command=migrate

      - name: django loaddata 
        django_manage: app_path=/mos 
                       fixtures='core/fixtures/default_choices.json members/fixtures/default_choices.json members/fixtures/dummy_members.json cal/fixtures/events_2012-09-20.json'
                       command=loaddata 

# set the default directory to /mos
      - lineinfile: dest=/home/vagrant/.bashrc
                    line='cd /mos'
